import type { GuideMeta } from "@/lib/content/types";

const UPDATED = "2026-10-09";

export const guides: GuideMeta[] = [
  {
    slug: "send-money-uae-to-pakistan",
    title: "Cheapest ways to send money from the UAE to Pakistan",
    seoTitle: "Send money UAE to Pakistan: compare the rate",
    description:
      "How to compare UAE remittance quotes by the rupees you actually receive. Fees, the exchange rate, and where to check a licensed channel.",
    category: "money",
    updated: UPDATED,
    countries: ["uae"],
    related: ["send-money-saudi-to-pakistan", "roshan-digital-account", "cost-of-living-dubai"],
    toolHref: "/tools/remittance",
    toolLabel: "Compare two remittance quotes",
    urTitle: "یو اے ای سے پاکستان پیسے بھیجنے کے سستے طریقے",
    urDescription:
      "فیس اور ریٹ ملا کر دیکھیں کتنے روپے بنتے ہیں۔ لائسنس شدہ چینل کہاں چیک کریں۔",
    featured: true,
  },
  {
    slug: "send-money-saudi-to-pakistan",
    title: "Cheapest ways to send money from Saudi Arabia to Pakistan",
    seoTitle: "Send money Saudi Arabia to Pakistan",
    description:
      "Compare Saudi remittance quotes by the rupees that land in Pakistan. What to ask the bank or exchange, and which official sites to trust.",
    category: "money",
    updated: UPDATED,
    countries: ["saudi-arabia"],
    related: ["send-money-uae-to-pakistan", "roshan-digital-account", "saudi-iqama-guide"],
    toolHref: "/tools/remittance",
    toolLabel: "Compare two remittance quotes",
    urTitle: "سعودی عرب سے پاکستان پیسے بھیجنے کے سستے طریقے",
    urDescription: "بینک یا ایکسچینج سے پوچھیں کتنے روپے ملیں گے۔ سرکاری ذرائع کے لنک۔",
    featured: true,
  },
  {
    slug: "genuine-dubai-job-from-pakistan",
    title: "How to find a genuine job in Dubai from Pakistan (and avoid fake agents)",
    seoTitle: "Genuine Dubai jobs from Pakistan",
    description:
      "A practical path from a real offer to a MOHRE contract, plus how to check an Overseas Employment Promoter and avoid fee-first scams.",
    category: "jobs",
    updated: UPDATED,
    countries: ["uae"],
    related: ["jobs-in-dubai-for-pakistanis", "fake-job-offer-dubai", "oep-licensed-agents"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
    urTitle: "پاکستان سے دبئی میں اصلی نوکری کیسے ڈھونڈیں",
    urDescription: "اصلی آفر سے محرے کنٹریکٹ تک، اور فیس پہلے مانگنے والے ایجنٹ سے بچاؤ۔",
    featured: true,
  },
  {
    slug: "uae-visit-visa-vs-work-visa",
    title: "UAE visit visa vs work visa for Pakistanis",
    seoTitle: "UAE visit visa vs work visa",
    description:
      "What a visit visa lets you do, what a work visa is for, and why working on a visit visa is a risk. Official places to confirm the current rule.",
    category: "visas",
    updated: UPDATED,
    countries: ["uae"],
    related: ["uae-visit-visa-for-pakistanis", "uae-work-visa-pakistan", "check-uae-visa-status"],
    toolHref: "/tools/gratuity-calculator",
    toolLabel: "UAE gratuity calculator",
    urTitle: "پاکستانیوں کے لیے یو اے ای ویزٹ ویزا بمقابلہ ورک ویزا",
    urDescription: "وزٹ ویزا کس کام کے لیے ہے، ورک ویزا کس کے لیے، اور سرکاری لنک۔",
    featured: true,
  },
  {
    slug: "saudi-iqama-guide",
    title: "Saudi Iqama guide for Pakistani workers",
    seoTitle: "Saudi Iqama guide for Pakistani workers",
    description:
      "What an Iqama is, who renews it, how to see the expiry, and which official Saudi portals to use. Fees are not guessed here.",
    category: "visas",
    updated: UPDATED,
    countries: ["saudi-arabia"],
    related: ["iqama-renewal", "check-iqama-status", "saudi-work-visa-pakistan"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
    urTitle: "پاکستانی کارکنوں کے لیے سعودی اقامہ گائیڈ",
    urDescription: "اقامہ کیا ہے، تجدید کون کرتا ہے، اور میعاد کہاں دیکھیں۔",
    featured: true,
  },
  {
    slug: "cost-of-living-dubai",
    title: "Cost of living in Dubai for a single Pakistani worker",
    seoTitle: "Cost of living in Dubai for one worker",
    description:
      "A planning budget for a single worker in Dubai: rent, food and transport. Figures are examples you can edit, not an official survey.",
    category: "cost",
    updated: UPDATED,
    countries: ["uae"],
    related: ["cost-of-living-riyadh", "jobs-in-dubai-for-pakistanis", "send-money-uae-to-pakistan"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
    urTitle: "دبئی میں اکیلی زندگی کا ماہانہ خرچ",
    urDescription: "کرایہ، کھانا اور سفر کی منصوبہ بندی۔ اعداد مثال ہیں، سرکاری سروے نہیں۔",
    featured: true,
  },
  {
    slug: "cost-of-living-riyadh",
    title: "Cost of living in Riyadh for a Pakistani family",
    seoTitle: "Cost of living in Riyadh for a family",
    description:
      "What usually drives a family budget in Riyadh: rent, school and a car. Use the editable estimate, and confirm school fees with the school.",
    category: "cost",
    updated: UPDATED,
    countries: ["saudi-arabia"],
    related: ["cost-of-living-dubai", "family-visa-uae-salary-requirement", "saudi-iqama-guide"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
    urTitle: "ریاض میں پاکستانی خاندان کا ماہانہ خرچ",
    urDescription: "کرایہ، سکول اور گاڑی۔ سکول فیس خود سکول سے پوچھیں۔",
    featured: true,
  },
  {
    slug: "uae-gratuity-rules",
    title: "Gratuity rules in the UAE explained",
    seoTitle: "UAE gratuity rules, with a calculator",
    description:
      "End-of-service gratuity under UAE Federal Decree-Law 33 of 2021: 21 days, then 30 days, and the two-year cap. An estimate, not a MOHRE ruling.",
    category: "rights",
    updated: UPDATED,
    countries: ["uae"],
    related: ["uae-work-visa-pakistan", "jobs-in-dubai-for-pakistanis", "genuine-dubai-job-from-pakistan"],
    toolHref: "/tools/gratuity-calculator",
    toolLabel: "Gratuity calculator",
    urTitle: "یو اے ای گریچویٹی کے قواعد",
    urDescription: "پہلے پانچ سال ۲۱ دن، اس کے بعد ۳۰ دن، اور دو سال کی حد۔ یہ اندازہ ہے۔",
    featured: true,
  },
  {
    slug: "gold-carry-dubai-saudi-pakistan",
    title: "How much gold can you carry from Dubai or Saudi Arabia to Pakistan",
    seoTitle: "Gold from Dubai or Saudi to Pakistan",
    description:
      "Why social-media gram limits are unreliable, and which Pakistan Customs and State Bank pages to check before you fly with gold.",
    category: "travel",
    updated: UPDATED,
    countries: ["uae", "saudi-arabia"],
    related: ["baggage-allowance-gulf-to-pakistan", "cheap-flights-dubai-to-pakistan", "send-money-uae-to-pakistan"],
    toolHref: "/gold-rates",
    toolLabel: "Today's gold rates",
    urTitle: "دبئی یا سعودی سے پاکستان کتنا سونا لے جا سکتے ہیں",
    urDescription: "سوشل میڈیا کی حد پر بھروسہ نہ کریں۔ کسٹمز اور اسٹیٹ بینک کے لنک۔",
    featured: true,
  },
  {
    slug: "roshan-digital-account",
    title: "Roshan Digital Account: a guide for overseas Pakistanis",
    seoTitle: "Roshan Digital Account for overseas Pakistanis",
    description:
      "What a Roshan Digital Account is for, who the State Bank says can open one, and why profit rates must be checked on the bank’s own page.",
    category: "money",
    updated: UPDATED,
    countries: ["uae", "saudi-arabia", "qatar", "kuwait", "oman", "bahrain"],
    related: ["send-money-uae-to-pakistan", "send-money-saudi-to-pakistan", "gold-carry-dubai-saudi-pakistan"],
    toolHref: "/rates",
    toolLabel: "Today's currency rates",
    urTitle: "روشن ڈیجیٹل اکاؤنٹ: بیرون ملک پاکستانیوں کے لیے",
    urDescription: "اکاؤنٹ کس کے لیے ہے، اور منافع کی شرح بینک کی ویب سائٹ پر دیکھیں۔",
    featured: true,
  },
  {
    slug: "uae-visit-visa-for-pakistanis",
    title: "UAE visit visa for Pakistanis 2026: requirements, fees, how to apply",
    seoTitle: "UAE visit visa for Pakistanis",
    description:
      "How Pakistanis apply for a UAE visit visa, what a sponsor or airline package usually asks for, and where to read the current fee yourself.",
    category: "visas",
    updated: UPDATED,
    countries: ["uae"],
    related: ["uae-visit-visa-vs-work-visa", "check-uae-visa-status", "uae-visa-renewal"],
    toolHref: "/rates/aed-to-pkr",
    toolLabel: "AED to PKR rate",
  },
  {
    slug: "uae-work-visa-pakistan",
    title: "How to get a UAE work visa from Pakistan",
    seoTitle: "UAE work visa from Pakistan",
    description:
      "The employer-led path: offer, MOHRE permission, entry, medical and Emirates ID. Plus the Pakistan Protector step for people going to work.",
    category: "visas",
    updated: UPDATED,
    countries: ["uae"],
    related: ["genuine-dubai-job-from-pakistan", "protector-of-emigrants", "gamca-medical-test"],
    toolHref: "/tools/gratuity-calculator",
    toolLabel: "Gratuity calculator",
  },
  {
    slug: "uae-visa-renewal",
    title: "UAE residence visa renewal: steps, documents, cost",
    seoTitle: "UAE residence visa renewal steps",
    description:
      "Who starts a UAE residence renewal, which documents usually come up, and why the fine for a late renewal must be read on ICP or GDRFA.",
    category: "visas",
    updated: UPDATED,
    countries: ["uae"],
    related: ["check-uae-visa-status", "uae-work-visa-pakistan", "family-visa-uae-salary-requirement"],
    toolHref: "/tools/gratuity-calculator",
    toolLabel: "Gratuity calculator",
  },
  {
    slug: "check-uae-visa-status",
    title: "How to check UAE visa status online with a passport number",
    seoTitle: "Check UAE visa status online",
    description:
      "Use ICP or GDRFA Dubai yourself. A screenshot from an agent is not proof of a visa file.",
    category: "visas",
    updated: UPDATED,
    countries: ["uae"],
    related: ["uae-visit-visa-for-pakistanis", "uae-visa-renewal", "fake-job-offer-dubai"],
    toolHref: "/rates/aed-to-pkr",
    toolLabel: "AED to PKR rate",
  },
  {
    slug: "saudi-visit-visa-for-pakistanis",
    title: "Saudi visit visa for Pakistanis: family, business, tourist",
    seoTitle: "Saudi visit visa for Pakistanis",
    description:
      "Family, business and tourist routes are not the same. Check the official visa site before you pay, because eligibility changes.",
    category: "visas",
    updated: UPDATED,
    countries: ["saudi-arabia"],
    related: ["saudi-work-visa-pakistan", "fake-saudi-visa-check", "check-iqama-status"],
    toolHref: "/rates/sar-to-pkr",
    toolLabel: "SAR to PKR rate",
  },
  {
    slug: "saudi-work-visa-pakistan",
    title: "Saudi work visa from Pakistan: process, Protector, medical",
    seoTitle: "Saudi work visa from Pakistan",
    description:
      "Offer, Wafid medical, Bureau of Emigration protector, and the visa itself. What to verify before you resign in Pakistan.",
    category: "visas",
    updated: UPDATED,
    countries: ["saudi-arabia"],
    related: ["gamca-medical-test", "protector-of-emigrants", "saudi-iqama-guide"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "iqama-renewal",
    title: "Iqama renewal: fees, Absher steps, late fine",
    seoTitle: "Iqama renewal fees and Absher steps",
    description:
      "Iqama renewal is usually the employer’s job on Muqeem or Absher. The late fine changes, so read it on the official screen, not in a group chat.",
    category: "visas",
    updated: UPDATED,
    countries: ["saudi-arabia"],
    related: ["check-iqama-status", "saudi-iqama-guide", "saudi-work-visa-pakistan"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "check-iqama-status",
    title: "Check Iqama status and expiry online",
    seoTitle: "Check Iqama status and expiry",
    description:
      "Where a worker can see Iqama expiry on Absher, and what the Muqeem portal is for. Do not share the one-time code.",
    category: "visas",
    updated: UPDATED,
    countries: ["saudi-arabia"],
    related: ["iqama-renewal", "saudi-iqama-guide", "fake-saudi-visa-check"],
    toolHref: "/rates/sar-to-pkr",
    toolLabel: "SAR to PKR rate",
  },
  {
    slug: "qatar-visa-for-pakistanis",
    title: "Qatar visa for Pakistanis: visit and work",
    seoTitle: "Qatar visa for Pakistanis",
    description:
      "Pakistanis need a visa for Qatar. Work residence is employer-sponsored. Confirm visit products on the Ministry of Interior portal.",
    category: "visas",
    updated: UPDATED,
    countries: ["qatar"],
    related: ["jobs-in-qatar-for-pakistanis", "gamca-medical-test", "protector-of-emigrants"],
    toolHref: "/rates/qar-to-pkr",
    toolLabel: "QAR to PKR rate",
  },
  {
    slug: "kuwait-visa-for-pakistanis",
    title: "Kuwait visa for Pakistanis: visit and work",
    seoTitle: "Kuwait visa for Pakistanis",
    description:
      "Kuwait work visas are sponsored. Check status on an official Ministry of Interior channel, not a forwarded PDF.",
    category: "visas",
    updated: UPDATED,
    countries: ["kuwait"],
    related: ["jobs-in-kuwait-for-pakistanis", "visa-agent-scam-pakistan", "protector-of-emigrants"],
    toolHref: "/rates/kwd-to-pkr",
    toolLabel: "KWD to PKR rate",
  },
  {
    slug: "oman-visa-for-pakistanis",
    title: "Oman visa for Pakistanis: visit and work",
    seoTitle: "Oman visa for Pakistanis",
    description:
      "Check Royal Oman Police for the visa your passport can actually get. Work visas are sponsored by the employer.",
    category: "visas",
    updated: UPDATED,
    countries: ["oman"],
    related: ["jobs-in-oman-for-pakistanis", "gamca-medical-test", "protector-of-emigrants"],
    toolHref: "/rates/omr-to-pkr",
    toolLabel: "OMR to PKR rate",
  },
  {
    slug: "bahrain-visa-for-pakistanis",
    title: "Bahrain visa for Pakistanis: visit and work",
    seoTitle: "Bahrain visa for Pakistanis",
    description:
      "Use Bahrain’s official eVisa or NPRA pages for visits, and LMRA rules for work permits. Do not pay a fee you cannot see on those sites.",
    category: "visas",
    updated: UPDATED,
    countries: ["bahrain"],
    related: ["visa-agent-scam-pakistan", "protector-of-emigrants", "gamca-medical-test"],
    toolHref: "/rates/bhd-to-pkr",
    toolLabel: "BHD to PKR rate",
  },
  {
    slug: "family-visa-uae-salary-requirement",
    title: "UAE family visa for Pakistanis: minimum salary and documents",
    seoTitle: "UAE family visa salary and documents",
    description:
      "ICP sets the minimum salary for family sponsorship and has changed it before. Read the current figure on the official page before you plan a move.",
    category: "visas",
    updated: UPDATED,
    countries: ["uae"],
    related: ["uae-visa-renewal", "cost-of-living-dubai", "uae-work-visa-pakistan"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "gamca-medical-test",
    title: "GAMCA / Wafid medical test for a Gulf visa: booking, fees, centres in Pakistan",
    seoTitle: "GAMCA Wafid medical test in Pakistan",
    description:
      "Book a Gulf work-visa medical only on the official Wafid portal. The fee is the one shown there, not a clinic’s WhatsApp price.",
    category: "visas",
    updated: UPDATED,
    countries: ["saudi-arabia", "uae", "qatar", "kuwait", "oman", "bahrain"],
    related: ["saudi-work-visa-pakistan", "protector-of-emigrants", "uae-work-visa-pakistan"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "protector-of-emigrants",
    title: "Protector stamp: Bureau of Emigration process and fees",
    seoTitle: "Protector of Emigrants stamp and fees",
    description:
      "Pakistanis going abroad on employment pass through the Bureau of Emigration. Check the live fee and the OEP licence on beoe.gov.pk.",
    category: "visas",
    updated: UPDATED,
    countries: ["uae", "saudi-arabia", "qatar", "kuwait", "oman", "bahrain"],
    related: ["oep-licensed-agents", "gamca-medical-test", "report-visa-fraud-fia"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "jobs-in-dubai-for-pakistanis",
    title: "Jobs in Dubai for Pakistanis 2026: how to apply and where to find genuine vacancies",
    seoTitle: "Jobs in Dubai for Pakistanis",
    description:
      "Where to look for Dubai jobs, how to read a basic salary, and how to confirm the company before you pay anyone.",
    category: "jobs",
    updated: UPDATED,
    countries: ["uae"],
    related: ["genuine-dubai-job-from-pakistan", "driver-jobs-in-dubai-salary", "gulf-cv-format"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "jobs-in-saudi-arabia-for-pakistanis",
    title: "Jobs in Saudi Arabia for Pakistanis: how to apply",
    seoTitle: "Jobs in Saudi Arabia for Pakistanis",
    description:
      "How Pakistani workers usually get a Saudi job, which portals matter after you arrive, and how to spot a fake contract.",
    category: "jobs",
    updated: UPDATED,
    countries: ["saudi-arabia"],
    related: ["saudi-work-visa-pakistan", "nurse-jobs-in-saudi-salary", "oep-licensed-agents"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "jobs-in-qatar-for-pakistanis",
    title: "Jobs in Qatar for Pakistanis: how to apply",
    seoTitle: "Jobs in Qatar for Pakistanis",
    description:
      "Apply to companies you can verify. A Qatar work residence comes from the employer, not from a fee paid in a market office.",
    category: "jobs",
    updated: UPDATED,
    countries: ["qatar"],
    related: ["qatar-visa-for-pakistanis", "electrician-jobs-in-gulf", "gulf-cv-format"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "jobs-in-kuwait-for-pakistanis",
    title: "Jobs in Kuwait for Pakistanis: how to apply",
    seoTitle: "Jobs in Kuwait for Pakistanis",
    description:
      "Kuwait hiring still runs through a sponsoring employer. Treat any request for a large upfront fee as a reason to stop.",
    category: "jobs",
    updated: UPDATED,
    countries: ["kuwait"],
    related: ["kuwait-visa-for-pakistanis", "electrician-jobs-in-gulf", "visa-agent-scam-pakistan"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "jobs-in-oman-for-pakistanis",
    title: "Jobs in Oman for Pakistanis: how to apply",
    seoTitle: "Jobs in Oman for Pakistanis",
    description:
      "Look for a named Omani employer and a contract you can read. Verify the route with the Ministry of Labour and the Protector in Pakistan.",
    category: "jobs",
    updated: UPDATED,
    countries: ["oman"],
    related: ["oman-visa-for-pakistanis", "gulf-cv-format", "oep-licensed-agents"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "driver-jobs-in-dubai-salary",
    title: "Driver jobs in Dubai: how to read the salary",
    seoTitle: "Driver jobs in Dubai: read the salary",
    description:
      "There is no single Dubai driver salary. Compare the basic wage on the MOHRE contract, plus housing, overtime and who pays the visa.",
    category: "jobs",
    updated: UPDATED,
    countries: ["uae"],
    related: ["jobs-in-dubai-for-pakistanis", "genuine-dubai-job-from-pakistan", "uae-gratuity-rules"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "nurse-jobs-in-saudi-salary",
    title: "Nurse jobs in Saudi Arabia: licence, hiring and pay",
    seoTitle: "Nurse jobs in Saudi Arabia",
    description:
      "Saudi hospitals hire against a health-commission classification. Confirm the licence path and read the wage on the contract, not in an ad.",
    category: "jobs",
    updated: UPDATED,
    countries: ["saudi-arabia"],
    related: ["jobs-in-saudi-arabia-for-pakistanis", "saudi-work-visa-pakistan", "gamca-medical-test"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "electrician-jobs-in-gulf",
    title: "Electrician jobs in the Gulf: papers, tests and contracts",
    seoTitle: "Electrician jobs in the Gulf",
    description:
      "Trade certificates, a possible skill test, and a contract that names basic pay. Do not start work before the residence permit allows it.",
    category: "jobs",
    updated: UPDATED,
    countries: ["uae", "saudi-arabia", "qatar", "kuwait", "oman", "bahrain"],
    related: ["jobs-in-dubai-for-pakistanis", "jobs-in-qatar-for-pakistanis", "gulf-cv-format"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "gulf-cv-format",
    title: "CV format for Gulf jobs (a simple template)",
    seoTitle: "CV format for Gulf jobs",
    description:
      "A one-page or two-page CV layout Gulf employers actually read: passport, trade, licence and real dates. Copy the headings.",
    category: "jobs",
    updated: UPDATED,
    countries: ["uae", "saudi-arabia", "qatar", "kuwait", "oman", "bahrain"],
    related: ["jobs-in-dubai-for-pakistanis", "jobs-in-saudi-arabia-for-pakistanis", "oep-licensed-agents"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "oep-licensed-agents",
    title: "How to check a licensed Overseas Employment Promoter in Pakistan",
    seoTitle: "Check a licensed OEP in Pakistan",
    description:
      "Use the Bureau of Emigration list to see if an agent’s licence is real and still valid before you pay.",
    category: "jobs",
    updated: UPDATED,
    countries: ["uae", "saudi-arabia", "qatar", "kuwait", "oman", "bahrain"],
    related: ["protector-of-emigrants", "visa-agent-scam-pakistan", "report-visa-fraud-fia"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "fake-job-offer-dubai",
    title: "How to spot a fake Dubai job offer letter",
    seoTitle: "Spot a fake Dubai job offer",
    description:
      "Warning signs on a Dubai offer: a free email, a fee before a MOHRE contract, and a company you cannot find.",
    category: "jobs",
    updated: UPDATED,
    countries: ["uae"],
    related: ["genuine-dubai-job-from-pakistan", "visa-agent-scam-pakistan", "jobs-in-dubai-for-pakistanis"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "visa-agent-scam-pakistan",
    title: "Visa agent scams in Pakistan: warning signs and where to complain",
    seoTitle: "Visa agent scams in Pakistan",
    description:
      "How fee-first visa agents work, what to keep as proof, and where the Bureau of Emigration and FIA fit in.",
    category: "visas",
    updated: UPDATED,
    countries: ["uae", "saudi-arabia", "qatar", "kuwait", "oman", "bahrain"],
    related: ["report-visa-fraud-fia", "oep-licensed-agents", "fake-job-offer-dubai"],
    toolHref: "/rates",
    toolLabel: "Currency rates",
  },
  {
    slug: "fake-saudi-visa-check",
    title: "How to verify a Saudi visa is genuine",
    seoTitle: "Verify a Saudi visa is genuine",
    description:
      "A PDF can be edited. Check the visa number on the official Saudi enquiry service before you book a flight.",
    category: "visas",
    updated: UPDATED,
    countries: ["saudi-arabia"],
    related: ["saudi-visit-visa-for-pakistanis", "saudi-work-visa-pakistan", "report-visa-fraud-fia"],
    toolHref: "/rates/sar-to-pkr",
    toolLabel: "SAR to PKR rate",
  },
  {
    slug: "report-visa-fraud-fia",
    title: "Report visa or job fraud to FIA and the Bureau of Emigration",
    seoTitle: "Report visa fraud to FIA",
    description:
      "What to collect before you complain, and the official doors at FIA and the Bureau of Emigration. A complaint is not a promise of a refund.",
    category: "rights",
    updated: UPDATED,
    countries: ["uae", "saudi-arabia", "qatar", "kuwait", "oman", "bahrain"],
    related: ["visa-agent-scam-pakistan", "oep-licensed-agents", "fake-job-offer-dubai"],
    toolHref: "/tools/salary-converter",
    toolLabel: "Salary converter",
  },
  {
    slug: "cheap-flights-dubai-to-pakistan",
    title: "Cheap flights Dubai to Lahore, Karachi, Islamabad and Peshawar",
    seoTitle: "Cheap flights Dubai to Pakistan",
    description:
      "How to compare Dubai–Pakistan fares without ignoring baggage. No magic cheapest month — Eid and school holidays cost more.",
    category: "travel",
    updated: UPDATED,
    countries: ["uae"],
    related: ["baggage-allowance-gulf-to-pakistan", "eid-flights-to-pakistan-tips", "cheap-flights-saudi-to-pakistan"],
    toolHref: "/tools/flights",
    toolLabel: "Flight notes",
  },
  {
    slug: "cheap-flights-saudi-to-pakistan",
    title: "Cheap flights from Riyadh, Jeddah and Dammam to Pakistan",
    seoTitle: "Cheap flights Saudi Arabia to Pakistan",
    description:
      "Which Saudi cities fly to Pakistan, and how to check a fare on the airline’s own site before you pay an agent.",
    category: "travel",
    updated: UPDATED,
    countries: ["saudi-arabia"],
    related: ["cheap-flights-dubai-to-pakistan", "baggage-allowance-gulf-to-pakistan", "eid-flights-to-pakistan-tips"],
    toolHref: "/tools/flights",
    toolLabel: "Flight notes",
  },
  {
    slug: "baggage-allowance-gulf-to-pakistan",
    title: "Baggage allowance on PIA, Emirates, flydubai, Air Arabia, Saudia and airblue",
    seoTitle: "Baggage allowance Gulf to Pakistan",
    description:
      "Allowance depends on the fare brand on your ticket. Lite fares can be cabin bag only. Read the airline page, not a forum.",
    category: "travel",
    updated: UPDATED,
    countries: ["uae", "saudi-arabia", "qatar", "kuwait", "oman", "bahrain"],
    related: ["cheap-flights-dubai-to-pakistan", "gold-carry-dubai-saudi-pakistan", "eid-flights-to-pakistan-tips"],
    toolHref: "/tools/flights",
    toolLabel: "Flight notes",
  },
  {
    slug: "eid-flights-to-pakistan-tips",
    title: "Eid flights to Pakistan: how to book without panic",
    seoTitle: "Eid flights to Pakistan: booking tips",
    description:
      "Eid dates follow the moon, fares rise early, and a WhatsApp ticket with no PNR is not a booking. Practical booking habits.",
    category: "travel",
    updated: UPDATED,
    countries: ["uae", "saudi-arabia", "qatar", "kuwait", "oman", "bahrain"],
    related: ["cheap-flights-dubai-to-pakistan", "cheap-flights-saudi-to-pakistan", "baggage-allowance-gulf-to-pakistan"],
    toolHref: "/tools/flights",
    toolLabel: "Flight notes",
  },
  {
    slug: "hajj-umrah-from-the-gulf",
    title: "Hajj and Umrah from the Gulf for Pakistanis",
    seoTitle: "Hajj and Umrah from the Gulf",
    description:
      "Nusuk and Pakistan’s Ministry of Religious Affairs do not run the same process. Check both before you pay a package.",
    category: "hajj",
    updated: UPDATED,
    countries: ["uae", "saudi-arabia", "qatar", "kuwait", "oman", "bahrain"],
    related: ["pakistan-government-hajj-scheme", "umrah-from-uae-on-nusuk", "saudi-visit-visa-for-pakistanis"],
    toolHref: "/rates/sar-to-pkr",
    toolLabel: "SAR to PKR rate",
  },
  {
    slug: "pakistan-government-hajj-scheme",
    title: "Pakistan’s government Hajj scheme for workers in the Gulf",
    seoTitle: "Pakistan government Hajj from the Gulf",
    description:
      "The Ministry of Religious Affairs scheme is not Nusuk. What the 2027–2030 policy prices, and where a Gulf worker should pay.",
    category: "hajj",
    updated: UPDATED,
    countries: ["uae", "saudi-arabia", "qatar", "kuwait", "oman", "bahrain"],
    related: ["hajj-umrah-from-the-gulf", "umrah-from-uae-on-nusuk", "saudi-visit-visa-for-pakistanis"],
    toolHref: "/rates/sar-to-pkr",
    toolLabel: "SAR to PKR rate",
    urTitle: "خلیج سے پاکستان کی سرکاری حج اسکیم",
    urDescription: "وزارت مذہبی امور کی اسکیم نسک نہیں۔ ادائیگی صرف سرکاری پورٹل پر۔",
  },
  {
    slug: "umrah-from-uae-on-nusuk",
    title: "Umrah from the UAE on Nusuk for Pakistani residents",
    seoTitle: "Umrah from the UAE on Nusuk",
    description:
      "How a Pakistani living in the UAE books Umrah on Nusuk, what a package must name, and why that is not Pakistan’s Hajj queue.",
    category: "hajj",
    updated: UPDATED,
    countries: ["uae", "saudi-arabia"],
    related: ["hajj-umrah-from-the-gulf", "pakistan-government-hajj-scheme", "cheap-flights-saudi-to-pakistan"],
    toolHref: "/rates/sar-to-pkr",
    toolLabel: "SAR to PKR rate",
    urTitle: "یو اے ای سے نسک پر عمرہ",
    urDescription: "دبئی یا ابوظہبی سے عمرہ نسک پر۔ پاکستان کی حج قطار الگ ہے۔",
  },
];

export function guideBySlug(slug: string) {
  return guides.find((guide) => guide.slug === slug) ?? null;
}

export function guidesInCategory(category: string) {
  return guides.filter((guide) => guide.category === category);
}
