/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BahrainRouteImport } from './routes/bahrain'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as KuwaitRouteImport } from './routes/kuwait'
import { Route as OmanRouteImport } from './routes/oman'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QatarRouteImport } from './routes/qatar'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SaudiArabiaRouteImport } from './routes/saudi-arabia'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UaeRouteImport } from './routes/uae'
import { Route as UrRouteImport } from './routes/ur'
import { Route as GoldRatesIndexRouteImport } from './routes/gold-rates/index'
import { Route as GoldRatesPlaceRouteImport } from './routes/gold-rates/$place'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as RatesIndexRouteImport } from './routes/rates/index'
import { Route as RatesPairRouteImport } from './routes/rates/$pair'
import { Route as ToolsFlightsRouteImport } from './routes/tools/flights'
import { Route as ToolsGratuityCalculatorRouteImport } from './routes/tools/gratuity-calculator'
import { Route as ToolsRemittanceRouteImport } from './routes/tools/remittance'
import { Route as ToolsSalaryConverterRouteImport } from './routes/tools/salary-converter'
import { Route as UrIndexRouteImport } from './routes/ur/index'
import { Route as UrAboutRouteImport } from './routes/ur/about'
import { Route as UrBahrainRouteImport } from './routes/ur/bahrain'
import { Route as UrContactRouteImport } from './routes/ur/contact'
import { Route as UrDisclaimerRouteImport } from './routes/ur/disclaimer'
import { Route as UrEditorialRouteImport } from './routes/ur/editorial'
import { Route as UrKuwaitRouteImport } from './routes/ur/kuwait'
import { Route as UrOmanRouteImport } from './routes/ur/oman'
import { Route as UrPrivacyRouteImport } from './routes/ur/privacy'
import { Route as UrQatarRouteImport } from './routes/ur/qatar'
import { Route as UrSaudiArabiaRouteImport } from './routes/ur/saudi-arabia'
import { Route as UrTermsRouteImport } from './routes/ur/terms'
import { Route as UrUaeRouteImport } from './routes/ur/uae'
import { Route as UrGoldRatesIndexRouteImport } from './routes/ur/gold-rates/index'
import { Route as UrGoldRatesPlaceRouteImport } from './routes/ur/gold-rates/$place'
import { Route as UrGuidesIndexRouteImport } from './routes/ur/guides/index'
import { Route as UrGuidesSlugRouteImport } from './routes/ur/guides/$slug'
import { Route as UrRatesIndexRouteImport } from './routes/ur/rates/index'
import { Route as UrRatesPairRouteImport } from './routes/ur/rates/$pair'
import { Route as UrToolsFlightsRouteImport } from './routes/ur/tools/flights'
import { Route as UrToolsGratuityCalculatorRouteImport } from './routes/ur/tools/gratuity-calculator'
import { Route as UrToolsRemittanceRouteImport } from './routes/ur/tools/remittance'
import { Route as UrToolsSalaryConverterRouteImport } from './routes/ur/tools/salary-converter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BahrainRoute = BahrainRouteImport.update({
  id: '/bahrain',
  path: '/bahrain',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const KuwaitRoute = KuwaitRouteImport.update({
  id: '/kuwait',
  path: '/kuwait',
  getParentRoute: () => rootRouteImport,
} as any)
const OmanRoute = OmanRouteImport.update({
  id: '/oman',
  path: '/oman',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QatarRoute = QatarRouteImport.update({
  id: '/qatar',
  path: '/qatar',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudiArabiaRoute = SaudiArabiaRouteImport.update({
  id: '/saudi-arabia',
  path: '/saudi-arabia',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UaeRoute = UaeRouteImport.update({
  id: '/uae',
  path: '/uae',
  getParentRoute: () => rootRouteImport,
} as any)
const UrRoute = UrRouteImport.update({
  id: '/ur',
  path: '/ur',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldRatesIndexRoute = GoldRatesIndexRouteImport.update({
  id: '/gold-rates/',
  path: '/gold-rates/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldRatesPlaceRoute = GoldRatesPlaceRouteImport.update({
  id: '/gold-rates/$place',
  path: '/gold-rates/$place',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesIndexRoute = RatesIndexRouteImport.update({
  id: '/rates/',
  path: '/rates/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesPairRoute = RatesPairRouteImport.update({
  id: '/rates/$pair',
  path: '/rates/$pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFlightsRoute = ToolsFlightsRouteImport.update({
  id: '/tools/flights',
  path: '/tools/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsGratuityCalculatorRoute = ToolsGratuityCalculatorRouteImport.update({
  id: '/tools/gratuity-calculator',
  path: '/tools/gratuity-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRemittanceRoute = ToolsRemittanceRouteImport.update({
  id: '/tools/remittance',
  path: '/tools/remittance',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSalaryConverterRoute = ToolsSalaryConverterRouteImport.update({
  id: '/tools/salary-converter',
  path: '/tools/salary-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const UrIndexRoute = UrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UrRoute,
} as any)
const UrAboutRoute = UrAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => UrRoute,
} as any)
const UrBahrainRoute = UrBahrainRouteImport.update({
  id: '/bahrain',
  path: '/bahrain',
  getParentRoute: () => UrRoute,
} as any)
const UrContactRoute = UrContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => UrRoute,
} as any)
const UrDisclaimerRoute = UrDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => UrRoute,
} as any)
const UrEditorialRoute = UrEditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => UrRoute,
} as any)
const UrKuwaitRoute = UrKuwaitRouteImport.update({
  id: '/kuwait',
  path: '/kuwait',
  getParentRoute: () => UrRoute,
} as any)
const UrOmanRoute = UrOmanRouteImport.update({
  id: '/oman',
  path: '/oman',
  getParentRoute: () => UrRoute,
} as any)
const UrPrivacyRoute = UrPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => UrRoute,
} as any)
const UrQatarRoute = UrQatarRouteImport.update({
  id: '/qatar',
  path: '/qatar',
  getParentRoute: () => UrRoute,
} as any)
const UrSaudiArabiaRoute = UrSaudiArabiaRouteImport.update({
  id: '/saudi-arabia',
  path: '/saudi-arabia',
  getParentRoute: () => UrRoute,
} as any)
const UrTermsRoute = UrTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => UrRoute,
} as any)
const UrUaeRoute = UrUaeRouteImport.update({
  id: '/uae',
  path: '/uae',
  getParentRoute: () => UrRoute,
} as any)
const UrGoldRatesIndexRoute = UrGoldRatesIndexRouteImport.update({
  id: '/gold-rates/',
  path: '/gold-rates/',
  getParentRoute: () => UrRoute,
} as any)
const UrGoldRatesPlaceRoute = UrGoldRatesPlaceRouteImport.update({
  id: '/gold-rates/$place',
  path: '/gold-rates/$place',
  getParentRoute: () => UrRoute,
} as any)
const UrGuidesIndexRoute = UrGuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => UrRoute,
} as any)
const UrGuidesSlugRoute = UrGuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => UrRoute,
} as any)
const UrRatesIndexRoute = UrRatesIndexRouteImport.update({
  id: '/rates/',
  path: '/rates/',
  getParentRoute: () => UrRoute,
} as any)
const UrRatesPairRoute = UrRatesPairRouteImport.update({
  id: '/rates/$pair',
  path: '/rates/$pair',
  getParentRoute: () => UrRoute,
} as any)
const UrToolsFlightsRoute = UrToolsFlightsRouteImport.update({
  id: '/tools/flights',
  path: '/tools/flights',
  getParentRoute: () => UrRoute,
} as any)
const UrToolsGratuityCalculatorRoute =
  UrToolsGratuityCalculatorRouteImport.update({
    id: '/tools/gratuity-calculator',
    path: '/tools/gratuity-calculator',
    getParentRoute: () => UrRoute,
  } as any)
const UrToolsRemittanceRoute = UrToolsRemittanceRouteImport.update({
  id: '/tools/remittance',
  path: '/tools/remittance',
  getParentRoute: () => UrRoute,
} as any)
const UrToolsSalaryConverterRoute = UrToolsSalaryConverterRouteImport.update({
  id: '/tools/salary-converter',
  path: '/tools/salary-converter',
  getParentRoute: () => UrRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bahrain': typeof BahrainRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial': typeof EditorialRoute
  '/kuwait': typeof KuwaitRoute
  '/oman': typeof OmanRoute
  '/privacy': typeof PrivacyRoute
  '/qatar': typeof QatarRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saudi-arabia': typeof SaudiArabiaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/uae': typeof UaeRoute
  '/ur': typeof UrRouteWithChildren
  '/gold-rates/$place': typeof GoldRatesPlaceRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/rates/$pair': typeof RatesPairRoute
  '/tools/flights': typeof ToolsFlightsRoute
  '/tools/gratuity-calculator': typeof ToolsGratuityCalculatorRoute
  '/tools/remittance': typeof ToolsRemittanceRoute
  '/tools/salary-converter': typeof ToolsSalaryConverterRoute
  '/ur/about': typeof UrAboutRoute
  '/ur/bahrain': typeof UrBahrainRoute
  '/ur/contact': typeof UrContactRoute
  '/ur/disclaimer': typeof UrDisclaimerRoute
  '/ur/editorial': typeof UrEditorialRoute
  '/ur/kuwait': typeof UrKuwaitRoute
  '/ur/oman': typeof UrOmanRoute
  '/ur/privacy': typeof UrPrivacyRoute
  '/ur/qatar': typeof UrQatarRoute
  '/ur/saudi-arabia': typeof UrSaudiArabiaRoute
  '/ur/terms': typeof UrTermsRoute
  '/ur/uae': typeof UrUaeRoute
  '/gold-rates/': typeof GoldRatesIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/rates/': typeof RatesIndexRoute
  '/ur/': typeof UrIndexRoute
  '/ur/gold-rates/$place': typeof UrGoldRatesPlaceRoute
  '/ur/guides/$slug': typeof UrGuidesSlugRoute
  '/ur/rates/$pair': typeof UrRatesPairRoute
  '/ur/tools/flights': typeof UrToolsFlightsRoute
  '/ur/tools/gratuity-calculator': typeof UrToolsGratuityCalculatorRoute
  '/ur/tools/remittance': typeof UrToolsRemittanceRoute
  '/ur/tools/salary-converter': typeof UrToolsSalaryConverterRoute
  '/ur/gold-rates/': typeof UrGoldRatesIndexRoute
  '/ur/guides/': typeof UrGuidesIndexRoute
  '/ur/rates/': typeof UrRatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bahrain': typeof BahrainRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial': typeof EditorialRoute
  '/kuwait': typeof KuwaitRoute
  '/oman': typeof OmanRoute
  '/privacy': typeof PrivacyRoute
  '/qatar': typeof QatarRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saudi-arabia': typeof SaudiArabiaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/uae': typeof UaeRoute
  '/gold-rates/$place': typeof GoldRatesPlaceRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/rates/$pair': typeof RatesPairRoute
  '/tools/flights': typeof ToolsFlightsRoute
  '/tools/gratuity-calculator': typeof ToolsGratuityCalculatorRoute
  '/tools/remittance': typeof ToolsRemittanceRoute
  '/tools/salary-converter': typeof ToolsSalaryConverterRoute
  '/ur/about': typeof UrAboutRoute
  '/ur/bahrain': typeof UrBahrainRoute
  '/ur/contact': typeof UrContactRoute
  '/ur/disclaimer': typeof UrDisclaimerRoute
  '/ur/editorial': typeof UrEditorialRoute
  '/ur/kuwait': typeof UrKuwaitRoute
  '/ur/oman': typeof UrOmanRoute
  '/ur/privacy': typeof UrPrivacyRoute
  '/ur/qatar': typeof UrQatarRoute
  '/ur/saudi-arabia': typeof UrSaudiArabiaRoute
  '/ur/terms': typeof UrTermsRoute
  '/ur/uae': typeof UrUaeRoute
  '/gold-rates': typeof GoldRatesIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/rates': typeof RatesIndexRoute
  '/ur': typeof UrIndexRoute
  '/ur/gold-rates/$place': typeof UrGoldRatesPlaceRoute
  '/ur/guides/$slug': typeof UrGuidesSlugRoute
  '/ur/rates/$pair': typeof UrRatesPairRoute
  '/ur/tools/flights': typeof UrToolsFlightsRoute
  '/ur/tools/gratuity-calculator': typeof UrToolsGratuityCalculatorRoute
  '/ur/tools/remittance': typeof UrToolsRemittanceRoute
  '/ur/tools/salary-converter': typeof UrToolsSalaryConverterRoute
  '/ur/gold-rates': typeof UrGoldRatesIndexRoute
  '/ur/guides': typeof UrGuidesIndexRoute
  '/ur/rates': typeof UrRatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bahrain': typeof BahrainRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial': typeof EditorialRoute
  '/kuwait': typeof KuwaitRoute
  '/oman': typeof OmanRoute
  '/privacy': typeof PrivacyRoute
  '/qatar': typeof QatarRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saudi-arabia': typeof SaudiArabiaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/uae': typeof UaeRoute
  '/ur': typeof UrRouteWithChildren
  '/gold-rates/$place': typeof GoldRatesPlaceRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/rates/$pair': typeof RatesPairRoute
  '/tools/flights': typeof ToolsFlightsRoute
  '/tools/gratuity-calculator': typeof ToolsGratuityCalculatorRoute
  '/tools/remittance': typeof ToolsRemittanceRoute
  '/tools/salary-converter': typeof ToolsSalaryConverterRoute
  '/ur/about': typeof UrAboutRoute
  '/ur/bahrain': typeof UrBahrainRoute
  '/ur/contact': typeof UrContactRoute
  '/ur/disclaimer': typeof UrDisclaimerRoute
  '/ur/editorial': typeof UrEditorialRoute
  '/ur/kuwait': typeof UrKuwaitRoute
  '/ur/oman': typeof UrOmanRoute
  '/ur/privacy': typeof UrPrivacyRoute
  '/ur/qatar': typeof UrQatarRoute
  '/ur/saudi-arabia': typeof UrSaudiArabiaRoute
  '/ur/terms': typeof UrTermsRoute
  '/ur/uae': typeof UrUaeRoute
  '/gold-rates/': typeof GoldRatesIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/rates/': typeof RatesIndexRoute
  '/ur/': typeof UrIndexRoute
  '/ur/gold-rates/$place': typeof UrGoldRatesPlaceRoute
  '/ur/guides/$slug': typeof UrGuidesSlugRoute
  '/ur/rates/$pair': typeof UrRatesPairRoute
  '/ur/tools/flights': typeof UrToolsFlightsRoute
  '/ur/tools/gratuity-calculator': typeof UrToolsGratuityCalculatorRoute
  '/ur/tools/remittance': typeof UrToolsRemittanceRoute
  '/ur/tools/salary-converter': typeof UrToolsSalaryConverterRoute
  '/ur/gold-rates/': typeof UrGoldRatesIndexRoute
  '/ur/guides/': typeof UrGuidesIndexRoute
  '/ur/rates/': typeof UrRatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bahrain'
    | '/contact'
    | '/disclaimer'
    | '/editorial'
    | '/kuwait'
    | '/oman'
    | '/privacy'
    | '/qatar'
    | '/robots.txt'
    | '/saudi-arabia'
    | '/sitemap.xml'
    | '/terms'
    | '/uae'
    | '/ur'
    | '/gold-rates/$place'
    | '/guides/$slug'
    | '/rates/$pair'
    | '/tools/flights'
    | '/tools/gratuity-calculator'
    | '/tools/remittance'
    | '/tools/salary-converter'
    | '/ur/about'
    | '/ur/bahrain'
    | '/ur/contact'
    | '/ur/disclaimer'
    | '/ur/editorial'
    | '/ur/kuwait'
    | '/ur/oman'
    | '/ur/privacy'
    | '/ur/qatar'
    | '/ur/saudi-arabia'
    | '/ur/terms'
    | '/ur/uae'
    | '/gold-rates/'
    | '/guides/'
    | '/rates/'
    | '/ur/'
    | '/ur/gold-rates/$place'
    | '/ur/guides/$slug'
    | '/ur/rates/$pair'
    | '/ur/tools/flights'
    | '/ur/tools/gratuity-calculator'
    | '/ur/tools/remittance'
    | '/ur/tools/salary-converter'
    | '/ur/gold-rates/'
    | '/ur/guides/'
    | '/ur/rates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bahrain'
    | '/contact'
    | '/disclaimer'
    | '/editorial'
    | '/kuwait'
    | '/oman'
    | '/privacy'
    | '/qatar'
    | '/robots.txt'
    | '/saudi-arabia'
    | '/sitemap.xml'
    | '/terms'
    | '/uae'
    | '/gold-rates/$place'
    | '/guides/$slug'
    | '/rates/$pair'
    | '/tools/flights'
    | '/tools/gratuity-calculator'
    | '/tools/remittance'
    | '/tools/salary-converter'
    | '/ur/about'
    | '/ur/bahrain'
    | '/ur/contact'
    | '/ur/disclaimer'
    | '/ur/editorial'
    | '/ur/kuwait'
    | '/ur/oman'
    | '/ur/privacy'
    | '/ur/qatar'
    | '/ur/saudi-arabia'
    | '/ur/terms'
    | '/ur/uae'
    | '/gold-rates'
    | '/guides'
    | '/rates'
    | '/ur'
    | '/ur/gold-rates/$place'
    | '/ur/guides/$slug'
    | '/ur/rates/$pair'
    | '/ur/tools/flights'
    | '/ur/tools/gratuity-calculator'
    | '/ur/tools/remittance'
    | '/ur/tools/salary-converter'
    | '/ur/gold-rates'
    | '/ur/guides'
    | '/ur/rates'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bahrain'
    | '/contact'
    | '/disclaimer'
    | '/editorial'
    | '/kuwait'
    | '/oman'
    | '/privacy'
    | '/qatar'
    | '/robots.txt'
    | '/saudi-arabia'
    | '/sitemap.xml'
    | '/terms'
    | '/uae'
    | '/ur'
    | '/gold-rates/$place'
    | '/guides/$slug'
    | '/rates/$pair'
    | '/tools/flights'
    | '/tools/gratuity-calculator'
    | '/tools/remittance'
    | '/tools/salary-converter'
    | '/ur/about'
    | '/ur/bahrain'
    | '/ur/contact'
    | '/ur/disclaimer'
    | '/ur/editorial'
    | '/ur/kuwait'
    | '/ur/oman'
    | '/ur/privacy'
    | '/ur/qatar'
    | '/ur/saudi-arabia'
    | '/ur/terms'
    | '/ur/uae'
    | '/gold-rates/'
    | '/guides/'
    | '/rates/'
    | '/ur/'
    | '/ur/gold-rates/$place'
    | '/ur/guides/$slug'
    | '/ur/rates/$pair'
    | '/ur/tools/flights'
    | '/ur/tools/gratuity-calculator'
    | '/ur/tools/remittance'
    | '/ur/tools/salary-converter'
    | '/ur/gold-rates/'
    | '/ur/guides/'
    | '/ur/rates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BahrainRoute: typeof BahrainRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EditorialRoute: typeof EditorialRoute
  KuwaitRoute: typeof KuwaitRoute
  OmanRoute: typeof OmanRoute
  PrivacyRoute: typeof PrivacyRoute
  QatarRoute: typeof QatarRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SaudiArabiaRoute: typeof SaudiArabiaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UaeRoute: typeof UaeRoute
  UrRoute: typeof UrRouteWithChildren
  GoldRatesPlaceRoute: typeof GoldRatesPlaceRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  RatesPairRoute: typeof RatesPairRoute
  ToolsFlightsRoute: typeof ToolsFlightsRoute
  ToolsGratuityCalculatorRoute: typeof ToolsGratuityCalculatorRoute
  ToolsRemittanceRoute: typeof ToolsRemittanceRoute
  ToolsSalaryConverterRoute: typeof ToolsSalaryConverterRoute
  GoldRatesIndexRoute: typeof GoldRatesIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  RatesIndexRoute: typeof RatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bahrain': {
      id: '/bahrain'
      path: '/bahrain'
      fullPath: '/bahrain'
      preLoaderRoute: typeof BahrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuwait': {
      id: '/kuwait'
      path: '/kuwait'
      fullPath: '/kuwait'
      preLoaderRoute: typeof KuwaitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oman': {
      id: '/oman'
      path: '/oman'
      fullPath: '/oman'
      preLoaderRoute: typeof OmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qatar': {
      id: '/qatar'
      path: '/qatar'
      fullPath: '/qatar'
      preLoaderRoute: typeof QatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saudi-arabia': {
      id: '/saudi-arabia'
      path: '/saudi-arabia'
      fullPath: '/saudi-arabia'
      preLoaderRoute: typeof SaudiArabiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uae': {
      id: '/uae'
      path: '/uae'
      fullPath: '/uae'
      preLoaderRoute: typeof UaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ur': {
      id: '/ur'
      path: '/ur'
      fullPath: '/ur'
      preLoaderRoute: typeof UrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-rates/': {
      id: '/gold-rates/'
      path: '/gold-rates'
      fullPath: '/gold-rates/'
      preLoaderRoute: typeof GoldRatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-rates/$place': {
      id: '/gold-rates/$place'
      path: '/gold-rates/$place'
      fullPath: '/gold-rates/$place'
      preLoaderRoute: typeof GoldRatesPlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates/': {
      id: '/rates/'
      path: '/rates'
      fullPath: '/rates/'
      preLoaderRoute: typeof RatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates/$pair': {
      id: '/rates/$pair'
      path: '/rates/$pair'
      fullPath: '/rates/$pair'
      preLoaderRoute: typeof RatesPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/flights': {
      id: '/tools/flights'
      path: '/tools/flights'
      fullPath: '/tools/flights'
      preLoaderRoute: typeof ToolsFlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/gratuity-calculator': {
      id: '/tools/gratuity-calculator'
      path: '/tools/gratuity-calculator'
      fullPath: '/tools/gratuity-calculator'
      preLoaderRoute: typeof ToolsGratuityCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/remittance': {
      id: '/tools/remittance'
      path: '/tools/remittance'
      fullPath: '/tools/remittance'
      preLoaderRoute: typeof ToolsRemittanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/salary-converter': {
      id: '/tools/salary-converter'
      path: '/tools/salary-converter'
      fullPath: '/tools/salary-converter'
      preLoaderRoute: typeof ToolsSalaryConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ur/': {
      id: '/ur/'
      path: '/'
      fullPath: '/ur/'
      preLoaderRoute: typeof UrIndexRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/about': {
      id: '/ur/about'
      path: '/about'
      fullPath: '/ur/about'
      preLoaderRoute: typeof UrAboutRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/bahrain': {
      id: '/ur/bahrain'
      path: '/bahrain'
      fullPath: '/ur/bahrain'
      preLoaderRoute: typeof UrBahrainRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/contact': {
      id: '/ur/contact'
      path: '/contact'
      fullPath: '/ur/contact'
      preLoaderRoute: typeof UrContactRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/disclaimer': {
      id: '/ur/disclaimer'
      path: '/disclaimer'
      fullPath: '/ur/disclaimer'
      preLoaderRoute: typeof UrDisclaimerRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/editorial': {
      id: '/ur/editorial'
      path: '/editorial'
      fullPath: '/ur/editorial'
      preLoaderRoute: typeof UrEditorialRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/kuwait': {
      id: '/ur/kuwait'
      path: '/kuwait'
      fullPath: '/ur/kuwait'
      preLoaderRoute: typeof UrKuwaitRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/oman': {
      id: '/ur/oman'
      path: '/oman'
      fullPath: '/ur/oman'
      preLoaderRoute: typeof UrOmanRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/privacy': {
      id: '/ur/privacy'
      path: '/privacy'
      fullPath: '/ur/privacy'
      preLoaderRoute: typeof UrPrivacyRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/qatar': {
      id: '/ur/qatar'
      path: '/qatar'
      fullPath: '/ur/qatar'
      preLoaderRoute: typeof UrQatarRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/saudi-arabia': {
      id: '/ur/saudi-arabia'
      path: '/saudi-arabia'
      fullPath: '/ur/saudi-arabia'
      preLoaderRoute: typeof UrSaudiArabiaRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/terms': {
      id: '/ur/terms'
      path: '/terms'
      fullPath: '/ur/terms'
      preLoaderRoute: typeof UrTermsRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/uae': {
      id: '/ur/uae'
      path: '/uae'
      fullPath: '/ur/uae'
      preLoaderRoute: typeof UrUaeRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/gold-rates/': {
      id: '/ur/gold-rates/'
      path: '/gold-rates'
      fullPath: '/ur/gold-rates/'
      preLoaderRoute: typeof UrGoldRatesIndexRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/gold-rates/$place': {
      id: '/ur/gold-rates/$place'
      path: '/gold-rates/$place'
      fullPath: '/ur/gold-rates/$place'
      preLoaderRoute: typeof UrGoldRatesPlaceRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/guides/': {
      id: '/ur/guides/'
      path: '/guides'
      fullPath: '/ur/guides/'
      preLoaderRoute: typeof UrGuidesIndexRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/guides/$slug': {
      id: '/ur/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/ur/guides/$slug'
      preLoaderRoute: typeof UrGuidesSlugRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/rates/': {
      id: '/ur/rates/'
      path: '/rates'
      fullPath: '/ur/rates/'
      preLoaderRoute: typeof UrRatesIndexRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/rates/$pair': {
      id: '/ur/rates/$pair'
      path: '/rates/$pair'
      fullPath: '/ur/rates/$pair'
      preLoaderRoute: typeof UrRatesPairRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/tools/flights': {
      id: '/ur/tools/flights'
      path: '/tools/flights'
      fullPath: '/ur/tools/flights'
      preLoaderRoute: typeof UrToolsFlightsRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/tools/gratuity-calculator': {
      id: '/ur/tools/gratuity-calculator'
      path: '/tools/gratuity-calculator'
      fullPath: '/ur/tools/gratuity-calculator'
      preLoaderRoute: typeof UrToolsGratuityCalculatorRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/tools/remittance': {
      id: '/ur/tools/remittance'
      path: '/tools/remittance'
      fullPath: '/ur/tools/remittance'
      preLoaderRoute: typeof UrToolsRemittanceRouteImport
      parentRoute: typeof UrRoute
    }
    '/ur/tools/salary-converter': {
      id: '/ur/tools/salary-converter'
      path: '/tools/salary-converter'
      fullPath: '/ur/tools/salary-converter'
      preLoaderRoute: typeof UrToolsSalaryConverterRouteImport
      parentRoute: typeof UrRoute
    }
  }
}

interface UrRouteChildren {
  UrAboutRoute: typeof UrAboutRoute
  UrBahrainRoute: typeof UrBahrainRoute
  UrContactRoute: typeof UrContactRoute
  UrDisclaimerRoute: typeof UrDisclaimerRoute
  UrEditorialRoute: typeof UrEditorialRoute
  UrKuwaitRoute: typeof UrKuwaitRoute
  UrOmanRoute: typeof UrOmanRoute
  UrPrivacyRoute: typeof UrPrivacyRoute
  UrQatarRoute: typeof UrQatarRoute
  UrSaudiArabiaRoute: typeof UrSaudiArabiaRoute
  UrTermsRoute: typeof UrTermsRoute
  UrUaeRoute: typeof UrUaeRoute
  UrIndexRoute: typeof UrIndexRoute
  UrGoldRatesPlaceRoute: typeof UrGoldRatesPlaceRoute
  UrGuidesSlugRoute: typeof UrGuidesSlugRoute
  UrRatesPairRoute: typeof UrRatesPairRoute
  UrToolsFlightsRoute: typeof UrToolsFlightsRoute
  UrToolsGratuityCalculatorRoute: typeof UrToolsGratuityCalculatorRoute
  UrToolsRemittanceRoute: typeof UrToolsRemittanceRoute
  UrToolsSalaryConverterRoute: typeof UrToolsSalaryConverterRoute
  UrGoldRatesIndexRoute: typeof UrGoldRatesIndexRoute
  UrGuidesIndexRoute: typeof UrGuidesIndexRoute
  UrRatesIndexRoute: typeof UrRatesIndexRoute
}

const UrRouteChildren: UrRouteChildren = {
  UrAboutRoute: UrAboutRoute,
  UrBahrainRoute: UrBahrainRoute,
  UrContactRoute: UrContactRoute,
  UrDisclaimerRoute: UrDisclaimerRoute,
  UrEditorialRoute: UrEditorialRoute,
  UrKuwaitRoute: UrKuwaitRoute,
  UrOmanRoute: UrOmanRoute,
  UrPrivacyRoute: UrPrivacyRoute,
  UrQatarRoute: UrQatarRoute,
  UrSaudiArabiaRoute: UrSaudiArabiaRoute,
  UrTermsRoute: UrTermsRoute,
  UrUaeRoute: UrUaeRoute,
  UrIndexRoute: UrIndexRoute,
  UrGoldRatesPlaceRoute: UrGoldRatesPlaceRoute,
  UrGuidesSlugRoute: UrGuidesSlugRoute,
  UrRatesPairRoute: UrRatesPairRoute,
  UrToolsFlightsRoute: UrToolsFlightsRoute,
  UrToolsGratuityCalculatorRoute: UrToolsGratuityCalculatorRoute,
  UrToolsRemittanceRoute: UrToolsRemittanceRoute,
  UrToolsSalaryConverterRoute: UrToolsSalaryConverterRoute,
  UrGoldRatesIndexRoute: UrGoldRatesIndexRoute,
  UrGuidesIndexRoute: UrGuidesIndexRoute,
  UrRatesIndexRoute: UrRatesIndexRoute,
}

const UrRouteWithChildren = UrRoute._addFileChildren(UrRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BahrainRoute: BahrainRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  EditorialRoute: EditorialRoute,
  KuwaitRoute: KuwaitRoute,
  OmanRoute: OmanRoute,
  PrivacyRoute: PrivacyRoute,
  QatarRoute: QatarRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SaudiArabiaRoute: SaudiArabiaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UaeRoute: UaeRoute,
  UrRoute: UrRouteWithChildren,
  GoldRatesPlaceRoute: GoldRatesPlaceRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  RatesPairRoute: RatesPairRoute,
  ToolsFlightsRoute: ToolsFlightsRoute,
  ToolsGratuityCalculatorRoute: ToolsGratuityCalculatorRoute,
  ToolsRemittanceRoute: ToolsRemittanceRoute,
  ToolsSalaryConverterRoute: ToolsSalaryConverterRoute,
  GoldRatesIndexRoute: GoldRatesIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  RatesIndexRoute: RatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
